name: Wonderland CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check & Test with Gradle
        run: ./gradlew clean check
      - name: Build DoorKnob Authentication image
        run: |
          export IMAGE_TAG=$(echo ${RAW_TAG#refs/heads/} | tr / _)
          ./gradlew :doorknob-authentication:bootBuildImage \
            -PimageTag=${IMAGE_TAG}_${GITHUB_RUN_NUMBER} \
            -Pproduction \
            -PdockerToken=${{ secrets.DOCKER_TOKEN }}
